export type ShotClipReviewStatus = 'verified';

export interface ProjectShotClip {
  projectSlug: string;
  clipId: string;
  videoId: string;
  player: string;
  moment: string;
  zone: string;
  note: string;
  source: string;
  sourceUrl: string;
  start: number;
  end: number;
  reviewedAt: string;
  reviewStatus: ShotClipReviewStatus;
  verificationNote: string;
}

export const PROJECT_SHOT_CLIPS: readonly ProjectShotClip[] = [
  {
    projectSlug: 'soundscape',
    clipId: 'shot-lillard-okc-2019',
    videoId: 'HMm5NtXLVDY',
    player: 'Damian Lillard',
    moment: '2019 series clincher vs OKC',
    zone: 'Deep left wing',
    note: 'A long-range confidence shot from the same high-upside territory.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=HMm5NtXLVDY',
    start: 0,
    end: 32,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed as a compact live-possession window with the make and first replay; no intro card or commentary runoff.',
  },
  {
    projectSlug: 'aios',
    clipId: 'shot-curry-okc-2016',
    videoId: 'GEMVGHoenXM',
    player: 'Stephen Curry',
    moment: '2016 overtime winner at OKC',
    zone: 'Deep top wing',
    note: 'A pull-up from range: early, confident, and hard to guard.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=GEMVGHoenXM',
    start: 0,
    end: 30,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the live setup through the make and first replay, with no studio package at the selected start.',
  },
  {
    projectSlug: 'terrace',
    clipId: 'shot-allen-spurs-2013',
    videoId: 'ua_w5RxpFIQ',
    player: 'Ray Allen',
    moment: '2013 Finals Game 6 corner three',
    zone: 'Right corner',
    note: 'A precision reset shot: footwork, timing, and a clean release.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=ua_w5RxpFIQ',
    start: 2200,
    end: 2230,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA full-game source reviewed at the absolute 36:40 window; it begins on the possession and ends before extended commentary.',
  },
  {
    projectSlug: 'bidcamp',
    clipId: 'shot-lebron-pacers-2018',
    videoId: 'JYmejM38vKs',
    player: 'LeBron James',
    moment: '2018 Game 5 winner vs Indiana',
    zone: 'Above-the-break three',
    note: 'A late-clock launch: direct, decisive, and built on pressure.',
    source: 'ESPN on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=JYmejM38vKs',
    start: 26,
    end: 48,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official ESPN sequence reviewed with absolute seconds for the live setup, make, and first replay; the intro card is excluded.',
  },
  {
    projectSlug: 'fantasy',
    clipId: 'shot-kawhi-sixers-2019',
    videoId: '75iExVNvrWw',
    player: 'Kawhi Leonard',
    moment: '2019 Game 7 winner vs Philadelphia',
    zone: 'Left baseline wing',
    note: 'A high-arc shot from a tight angle with real consequence.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=75iExVNvrWw',
    start: 0,
    end: 36,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the live inbound through the make and first replay; the short window avoids broad series footage.',
  },
  {
    projectSlug: 'remodelvision',
    clipId: 'shot-kyrie-warriors-2016',
    videoId: 'fZ8yCJgsF_4',
    player: 'Kyrie Irving',
    moment: '2016 Finals Game 7 go-ahead three',
    zone: 'Right wing above the break',
    note: 'A high-skill isolation three with the title hanging on the possession.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=fZ8yCJgsF_4',
    start: 0,
    end: 34,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the isolation setup through the make and first replay; no broad highlight reel is used.',
  },
  {
    projectSlug: 'bballedu',
    clipId: 'shot-lillard-rockets-2014',
    videoId: 'mejFtEY5faU',
    player: 'Damian Lillard',
    moment: '2014 series clincher vs Houston',
    zone: 'Left wing three',
    note: 'A clean catch-and-fire ending from the left side of the floor.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=mejFtEY5faU',
    start: 10,
    end: 30,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed after the opening title card; the window starts on the live setup and stops after the make before runoff.',
  },
  {
    projectSlug: 'dispatches',
    clipId: 'shot-tatum-sixers-2023',
    videoId: 'NLOJvl98SwQ',
    player: 'Jayson Tatum',
    moment: '2023 Game 6 late three vs Philadelphia',
    zone: 'Left wing above the break',
    note: 'A cold-stretch breaker that kept the whole series alive.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=NLOJvl98SwQ',
    start: 52,
    end: 76,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the identified fourth-quarter run; the absolute 0:52 start avoids the preceding setup package.',
  },
  {
    projectSlug: 'book',
    clipId: 'shot-luka-clippers-2020',
    videoId: 'Mz3TBKrBp5M',
    player: 'Luka Doncic',
    moment: '2020 bubble winner vs LA Clippers',
    zone: 'Left wing stepback',
    note: 'A left-wing creation shot under playoff pressure.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=Mz3TBKrBp5M',
    start: 0,
    end: 36,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA every-angle source reviewed from the live possession through the make and first replay.',
  },
  {
    projectSlug: 'signal-lab',
    clipId: 'shot-haliburton-knicks-2025',
    videoId: 'XxSr2nArxkA',
    player: 'Tyrese Haliburton',
    moment: '2025 playoff four-point play vs New York',
    zone: 'Top-side pull-up',
    note: 'A modern shot-profile swing: space, nerve, and instant leverage.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=XxSr2nArxkA',
    start: 91,
    end: 124,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed at the absolute 1:31 start; it includes the live attack and finish without the earlier comeback package.',
  },
  {
    projectSlug: 'cap-fit-builder',
    clipId: 'shot-wade-warriors-2019',
    videoId: 'lm1wzEL8FZY',
    player: 'Dwyane Wade',
    moment: '2019 one-legged bank winner vs Golden State',
    zone: 'High right wing',
    note: 'A broken-play heave that turned improvisation into a highlight.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=lm1wzEL8FZY',
    start: 0,
    end: 29,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the live possession through the banked make and first replay.',
  },
  {
    projectSlug: 'clfe',
    clipId: 'shot-paul-spurs-2015',
    videoId: 'xb95YLw1bns',
    player: 'Chris Paul',
    moment: '2015 Game 7 winner vs San Antonio',
    zone: 'High right lane',
    note: 'A one-legged high-angle shot over elite defense.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=xb95YLw1bns',
    start: 62,
    end: 78,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed at the absolute 1:02 setup; it ends after the winning shot before extended reaction coverage.',
  },
  {
    projectSlug: 'rte',
    clipId: 'shot-brunson-sixers-2024',
    videoId: '782QfcAxH1Q',
    player: 'Jalen Brunson',
    moment: '2024 playoff pull-up run vs Philadelphia',
    zone: 'Left elbow pull-up',
    note: 'A compact guard shot from a playoff series built on counters.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=782QfcAxH1Q',
    start: 0,
    end: 34,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA game-winning sequence reviewed from the live setup through the make and first replay.',
  },
  {
    projectSlug: 'quality-runner',
    clipId: 'shot-fisher-spurs-2004',
    videoId: 'p-u4pIQyjfE',
    player: 'Derek Fisher',
    moment: '2004 0.4-second winner vs San Antonio',
    zone: 'Left baseline catch',
    note: 'A near-impossible release from the baseline side.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=p-u4pIQyjfE',
    start: 0,
    end: 24,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the inbound through the 0.4-second make and first replay.',
  },
  {
    projectSlug: 'eslint-plugin-anti-slop',
    clipId: 'shot-booker-clippers-2020',
    videoId: '0mU-bEOPujM',
    player: 'Devin Booker',
    moment: '2020 bubble winner vs LA Clippers',
    zone: 'Left baseline fade',
    note: 'A contested baseline touch shot with no clean landing space.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=0mU-bEOPujM',
    start: 0,
    end: 35,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA every-angle source reviewed from the live baseline possession through the make and first replay.',
  },
  {
    projectSlug: 'agent-eval-contract',
    clipId: 'shot-reggie-knicks-1995',
    videoId: 'MRLysMEHokI',
    player: 'Reggie Miller',
    moment: '1995 eight-points-in-nine-seconds three',
    zone: 'Above-the-break three',
    note: 'A pressure swing shot where momentum flipped instantly.',
    source: 'Indiana Pacers on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=MRLysMEHokI',
    start: 42,
    end: 62,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official Indiana Pacers source rechecked at the live sequence start; the window begins before the first three and ends after the eight-point run before extended commentary.',
  },
  {
    projectSlug: 'research-domain-writing',
    clipId: 'shot-wade-celtics-ot',
    videoId: 'AjGvr-oSo88',
    player: 'Dwyane Wade',
    moment: 'Crazy overtime jumper vs Boston',
    zone: 'Right lane pull-up',
    note: 'A downhill guard shot from the boundary between paint and midrange.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=AjGvr-oSo88',
    start: 0,
    end: 20,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA source reviewed from the live creation sequence through the overtime make and immediate replay.',
  },
  {
    projectSlug: 'tmcp',
    clipId: 'shot-parker-heat-2013',
    videoId: 'oRFiKbI5CXc',
    player: 'Tony Parker',
    moment: '2013 Finals Game 1 falling jumper',
    zone: 'High lane floater',
    note: 'A balance-breaking shot that used time, angle, and touch.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=oRFiKbI5CXc',
    start: 0,
    end: 34,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA every-angle source reviewed from the live attack through the falling make and first replay.',
  },
  {
    projectSlug: 'pre-cr-suite',
    clipId: 'shot-rose-cavs-2015',
    videoId: 'wd3mxCQlve4',
    player: 'Derrick Rose',
    moment: '2015 banked winner vs Cleveland',
    zone: 'Left wing bank',
    note: 'A sudden midrange-window shot that turned a broken possession into a roar.',
    source: 'NBA on YouTube',
    sourceUrl: 'https://www.youtube.com/watch?v=wd3mxCQlve4',
    start: 0,
    end: 34,
    reviewedAt: '2026-07-21',
    reviewStatus: 'verified',
    verificationNote:
      'Official NBA every-angle source reviewed from the live possession through the banked make and first replay.',
  },
] as const;

export const PROJECT_SHOT_CLIPS_BY_SLUG: Readonly<Record<string, ProjectShotClip>> =
  Object.fromEntries(PROJECT_SHOT_CLIPS.map((clip) => [clip.projectSlug, clip]));

export function getProjectShotClip(projectSlug: string): ProjectShotClip | undefined {
  return PROJECT_SHOT_CLIPS_BY_SLUG[projectSlug];
}
